image: archlinux
packages:
  - nodejs
  - npm
sources:
  - https://git.sr.ht/~robinheghan/glogg
tasks:
  - setup: |
      cd glogg
      npm ci
  - build: |
      cd glogg
      npm run format:check
      npm test
