name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    shell: bash

jobs:
  validate-code-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - run: npm ci

      - run: npm run format:check

  build:
    needs: validate-code-formatting

    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "macOS-latest", "ubuntu-latest"]
        node-version: [20.x, 22.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci

      - run: npm test
