name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: ["windows-latest", "macOS-latest", "ubuntu-latest"]
        node-version: [18.x, 20.x, 22.x]

    runs-on: ${{ matrix.os }}
    shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci

      - run: npm run format:check

      - run: npm test
